import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const satoshi = localFont({
  src: [
    { path: "../../public/fonts/Satoshi-Regular.otf", weight: "400" },
    { path: "../../public/fonts/Satoshi-Medium.otf", weight: "500" },
    { path: "../../public/fonts/Satoshi-Bold.otf", weight: "700" },
  ],
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "ITMO Workspace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${satoshi.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-satoshi bg-[#F7F9FA]">
        {children}
      </body>
    </html>
  );
}
